[colors.primary]
background = "#1e2030"
foreground = "#cad3f5"

[colors.cursor]
text = "#1e2030"
cursor = "#f4dbd6" # Rosewater

[colors.vi_mode_cursor]
text = "#1e2030"
cursor = "#b7bdf8" # Lavender

[colors.search.matches]
foreground = "#1e2030"
background = "#eed49f" # Yellow

[colors.search.focused_match]
foreground = "#1e2030"
background = "#f5a97f" # Peach

[colors.footer_bar]
foreground = "#1e2030"
background = "#cad3f5"

[colors.selection]
text = "#cad3f5"
background = "#5b6078" # Surface 1

[colors.normal]
black = "#494d64"   # Surface 1
red = "#ed8796"     # Red
green = "#a6da95"   # Green
yellow = "#eed49f"  # Yellow
blue = "#8aadf4"    # Blue
magenta = "#f5bde6" # Pink
cyan = "#8bd5ca"    # Teal
white = "#b8c0e0"   # Subtext 1

[colors.bright]
black = "#5b6078"   # Surface 2
red = "#ed8796"     # Red
green = "#a6da95"   # Green
yellow = "#eed49f"  # Yellow
blue = "#8aadf4"    # Blue
magenta = "#f5bde6" # Pink
cyan = "#8bd5ca"    # Teal
white = "#a5adcb"   # Subtext 0