# Catppuccin Macchiato Palette
$activeBorderColor = rgb(c6a0f6)    # Mauve
$inactiveBorderColor = rgb(494d64)  # Surface 1

general {
    gaps_in = 3     # Space between windows
    gaps_out = 5    # Space between windows and screen edges/bar
    border_size = 2
    col.active_border = rgb(c29df2)
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

animations {
    enabled = yes
    bezier = calm, 0.25, 0.9, 0.35, 1

    animation = windows,     1, 4, calm
    animation = windowsIn,   1, 4, calm
    animation = windowsOut,  1, 3, calm
    animation = windowsMove, 1, 4, calm
    animation = fade,        1, 3, calm
    animation = fadeIn,      1, 3, calm
    animation = fadeOut,     1, 2, calm
    animation = layers,      1, 3, calm
    animation = layersIn,    1, 3, calm
    animation = layersOut,   1, 2, calm
    animation = workspaces,  1, 4, calm
}

decoration {
    # High Roundness for the "Pill" look
    rounding = 12
    # Note: No transparency as requested
    blur {
        enabled = false
    }
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
    
    groupbar {
        col.active = $activeBorderColor
        col.inactive = $inactiveBorderColor
    }
}



# ────────────────────────────────────────────────────────────
# Ghostty Size & Position Fix
# ────────────────────────────────────────────────────────────
windowrule = match:class com.mitchellh.ghostty, size 960x640
windowrule = match:class com.mitchellh.ghostty, center on

# ────────────────────────────────────────────────────────────
# Game Opacity - Full opacity for video games
# ────────────────────────────────────────────────────────────
windowrule = opacity 1.0 override, match:content game


# ────────────────────────────────────────────────────────────
# Layer Rules
# ────────────────────────────────────────────────────────────


layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0, match:namespace walker
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur on, match:namespace vicinae
layerrule = blur on, match:namespace swayosd
layerrule = ignore_alpha 0.1, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace vicinae