source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    # Using your Macchiato Base
    color = rgb(30, 32, 48)
    path = ~/.config/omarchy/current/background
    blur_passes = 3
    blur_size = 7
}

animations {
    enabled = true
}

input-field {
    monitor =
    size = 300, 60
    position = 0, -80
    halign = center
    valign = center

    # Glassmorphism colors
    inner_color = rgba(30, 32, 48, 0.5)
    outer_color = rgb(194, 157, 242) # Your Theme Border (#c29df2)
    outline_thickness = 2

    font_family = JetBrainsMono Nerd Font
    font_color = rgb(202, 211, 245) # Macchiato Text

    placeholder_text = <span foreground="##cad3f5">Enter Password</span>
    check_color = rgb(190, 154, 238) # Your Active Purple (#be9aee)
    fail_color = rgb(237, 135, 150)  # Macchiato Red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    # THIS MAKES IT A PILL
    rounding = 999
    
    shadow_passes = 2
    fade_on_empty = false
}

# Optional: Adding a clock to make it look modern
label {
    monitor =
    text = $TIME
    color = rgb(202, 211, 245)
    font_size = 64
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = false
}