include=~/.local/share/omarchy/default/mako/core.ini

# --- Omarchy Macchiato: Round Edition ---
text-color=#cad3f5
background-color=#1e2030
border-color=#c29df2
border-size=2

# This matches your OSD and Waybar roundness
border-radius=20

# Optional: Add icons to the notifications if they are missing
max-icon-size=48
default-timeout=5000